server:
  port: 8082

postgres:
  configuration:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.web: DEBUG